version: '2'
services:
  proofs:
    image: 'blockstack-proof-validator:latest'
    expose:
      - 5000
  nginx:
    image: 'nginx:latest'
    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - /etc/ssl/private/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - 80:80
      - 443:443
